# Generated by Django 3.2.9 on 2021-12-03 11:07

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211202_0627'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='good',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('sites')),
            ],
        ),
        migrations.AlterModelManagers(
            name='partition',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
